# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b74894812bfd25e49c52251cf9ee8d8368a128643d62f7c0e088bb13aac14b88c3f11d171c89971a3b328ed17c57e5ebdbb067c2fc94db04092414fdb3c8cc85

test:
  secret_key_base: 303f16ebe607d042b8807f95d62f685366b82b3c86479fc87df1acb3283043709efa382fa47e9c75036ae71c36db1cc6750f0aa6c142817f5176a3c1eab7a3df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
